[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace nRF82840_xxAA with your chip as listed in `probe-rs-cli chip list`
runner = "probe-run --chip nRF52833_xxAA"

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "info"
